def options(ctx):
    pass   

def configure(ctx):
    pass

def build(ctx):
	ctx(rule='jshint ${SRC}', source='../lib/nmea001.js')
	ctx(rule='mocha --ui tdd -R list ${SRC}',source='nmea.test.js')


	
